name: finance_dwh
version: '1.0.0'
config-version: 2

profile: finance_dwh

model-paths: ["models"]
seed-paths:  ["seeds"]
test-paths:  ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  finance_dwh:
    staging:
      +materialized: view
    ods:
      +materialized: table
    dds:
      +materialized: table
      +schema: dds
      dims:
        +engine: "ReplacingMergeTree(_loaded_at_ts)"
      facts:
        +materialized: incremental
        +incremental_strategy: delete+insert
        +engine: "MergeTree()"
      intermediate:
        +schema: dds
        +materialized: table
    marts:
      +materialized: table
      +schema: dm
      +engine: "MergeTree()"
      +tags: ["dm"]
